package com.urcodebin.api.dto;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateTimeSerializer;
import com.urcodebin.api.enums.PasteSyntax;
import com.urcodebin.api.enums.PasteVisibility;

import java.time.LocalDateTime;
import java.util.UUID;

public class CodePasteDTO {

    @JsonProperty("paste_id")
    private UUID pasteId;

    @JsonProperty("source_code")
    @JsonSetter(nulls = Nulls.SKIP)
    private String sourceCode;

    @JsonProperty("paste_title")
    @JsonSetter(nulls = Nulls.SKIP)
    private String pasteTitle;

    @JsonProperty("paste_syntax")
    @JsonSetter(nulls = Nulls.SKIP)
    private PasteSyntax pasteSyntax;

    @JsonProperty("paste_expiration_date")
    @JsonSetter(nulls = Nulls.SKIP)
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonSerialize(using = LocalDateTimeSerializer.class)
    private LocalDateTime pasteExpirationDate;

    @JsonProperty("paste_visibility")
    @JsonSetter(nulls = Nulls.SKIP)
    private PasteVisibility pasteVisibility;

    public UUID getPasteId() {
        return UUID.fromString(pasteId.toString());
    }

    private void setPasteId(UUID pasteId) {
        this.pasteId = UUID.fromString(pasteId.toString());
    }

    public String getSourceCode() {
        return sourceCode;
    }

    private void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode;
    }

    public String getPasteTitle() {
        return pasteTitle;
    }

    private void setPasteTitle(String pasteTitle) {
        this.pasteTitle = pasteTitle;
    }

    public PasteSyntax getPasteSyntax() {
        return pasteSyntax;
    }

    private void setPasteSyntax(PasteSyntax pasteSyntax) {
        this.pasteSyntax = pasteSyntax;
    }

    public LocalDateTime getPasteExpirationDate() {
        return LocalDateTime.from(pasteExpirationDate);
    }

    private void setPasteExpirationDate(LocalDateTime pasteExpirationDate) {
        this.pasteExpirationDate = LocalDateTime.from(pasteExpirationDate);
    }

    public PasteVisibility getPasteVisibility() {
        return pasteVisibility;
    }

    private void setPasteVisibility(PasteVisibility pasteVisibility) {
        this.pasteVisibility = pasteVisibility;
    }

    /**
     * Builder used for creating a CodePasteDTO objects. After
     * build() is called, it will return an immutable CodePasteDTO
     * object generated by the user.
     */
    public static class Builder {

        private final CodePasteDTO codePaste;

        public Builder() {
            codePaste = new CodePasteDTO();
        }

        public Builder setPasteTitle(String pasteTitle) {
            codePaste.setPasteTitle(pasteTitle);
            return this;
        }

        public Builder setPasteSyntax(PasteSyntax pasteSyntax) {
            codePaste.setPasteSyntax(pasteSyntax);
            return this;
        }

        public Builder setPasteVisibility(PasteVisibility pasteVisibility) {
            codePaste.setPasteVisibility(pasteVisibility);
            return this;
        }

        public Builder setPasteExpiration(LocalDateTime pasteExpiration) {
            codePaste.setPasteExpirationDate(pasteExpiration);
            return this;
        }

        public Builder setSourceCode(String sourceCode) {
            codePaste.setSourceCode(sourceCode);
            return this;
        }

        public Builder setPasteId(UUID pasteId) {
            codePaste.setPasteId(pasteId);
            return this;
        }

        public CodePasteDTO build() {
            return codePaste;
        }

    }
}
